---
name: container image

on:
  push:
  pull_request:
  schedule:
  - cron: '0 20 * * 5'

jobs:
  docker-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: docker/setup-qemu-action@v3.2.0
    - uses: docker/setup-buildx-action@v3.8.0
    # > By default, this action uses the Git context so you don't need to use
    # > the actions/checkout action to checkout the repository because this
    # > will be done directly by buildkit. [...]
    # > any file mutation in the steps that precede [...] will be ignored,
    # > including processing of the .dockerignore file
    # https://github.com/marketplace/actions/build-and-push-docker-images
    # > The commit history is not preserved.
    # https://docs.docker.com/engine/reference/commandline/build/#git-repositories
    - uses: docker/build-push-action@v6.9.0
      with:
        file: Containerfile
        platforms: |
          linux/amd64
          linux/arm/v6
          linux/arm/v7
          linux/arm64
